[params]
  ShowToc = true         # Exibe o sum치rio lateral no post
  TocOpen = true         # Sum치rio j치 vem aberto
[taxonomies]
  tag = "tags"
  category = "categories"
[[menu.main]]
  name = "Categorias"
  url = "/categories/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2
  
  [[menu.main]]
  name = "Filosofia"
  url = "/filosofia/"
  weight = 3
[params.homeInfoParams]
  Title = "zlogik"
  Content = "Estudos filos칩ficos organizados por tema, autor e conceito."
